<?php

namespace ES\OperatoriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseCategoriaRepository extends EntityRepository
{
}
