<?php

namespace ES\OperatoriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RichiestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RichiestaRepository extends EntityRepository {

    public function filtro($request) {
        $qb = $this->createQueryBuilder('r')
                ->where('r.user is null');
        $filtro = false;
        if (isset($request['ragione_sociale'])) {
            $qb->andWhere('(r.ragione_sociale LIKE :nome OR r.referente LIKE :nome)')
                    ->setParameter('nome', "%{$request['ragione_sociale']}%");
            $filtro = true;
        }
        if (isset($request['partita_iva'])) {
            $qb->andWhere('(r.partita_iva LIKE :piva OR r.codice_fiscale LIKE :piva)')
                    ->setParameter('piva', "%{$request['partita_iva']}%");
            $filtro = true;
        }
        if(!$filtro) {
            $qb->andWhere('(r.attivita_principale != :anga)')
                    ->setParameter('anga', "anga");
        }
        $qb->orderBy('r.id', 'desc');
        return $qb->getQuery()->execute();
        
    }

}
