<?php

namespace ES\OperatoriBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository {

    public function cancella($sr_id) {
        $query = $this->getEntityManager()->createQuery(
                'DELETE ESOperatoriBundle:Tag t 
                  WHERE t.showroom = :sr_id'
        );
        $query->setParameter('sr_id', $sr_id);
        return $query->execute();
    }

}
