<?php

namespace ES\CerMapBundle\Entity\Mps;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRifiutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{
}