<?php

namespace ES\CerMapBundle\Entity\Mps;

/**
 * MateriaPrimaSecondaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpsRepository extends MpsMotore {

    public function cercaAutocomplete($nome) {
        $q = $this->createQueryBuilder('mps')
                ->where('mps.materia LIKE :materia')
                ->orderBy('mps.materia', 'ASC');
        $dql = $this->getEntityManager()->createQuery($q->getDQL());
        $dql->setParameter('materia', $nome . '%');
        $results = $dql->execute(); //getResult();
        $out = array();
        foreach ($results as $result) {
            $out[] = array(
                'id' => $result->getId(),
                'label' => "[{$result->getCategoria()->getNome()}] {$result->getMateria()}",
                'value' => $result->getMateria(),
                'materia' => $result->getMateria(),
                'descrizione' => $result->getDescrizione(),
                'categoria' => $result->getCategoria()->getId(),
            );
        }
        return $out;
    }

    public function all() {
        $q = $this->_all();
        $dql = $this->getEntityManager()->createQuery($q->getDQL());
        return $dql->execute(); //getResult();
    }
    
    public function _all() {
        return $this->createQueryBuilder('mps')
                ->leftJoin('mps.categoria', 'c')
                ->orderBy('c.nome ASC, mps.materia', 'ASC')
                ;
    }

}