<?php

namespace ES\MessengerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * destinatarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllegatoRepository extends EntityRepository
{
}