<?php

namespace ES\MessengerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CerchiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CerchiaRepository extends EntityRepository {

    public function cancellaContattiCerchia(Cerchia $cerchia) {
        $connection = $this->getEntityManager()->getConnection();
        $q = "DELETE FROM msg_cerchie_contatti WHERE cerchia_id = ".$cerchia->getId();
        $connection->executeUpdate($q);
    }

}