<?php

namespace ES\MessengerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RispostaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RispostaRepository extends EntityRepository
{
}