<?php

namespace ES\MessengerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RubricaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubricaRepository extends EntityRepository {
    
     public function ricerca_per_lettera(\ES\UserBundle\Entity\User $utente, $contatti,$lettera) {
        $q = $this->createQueryBuilder('m');
        $q->leftJoin('m.contatto', 'u');    //utente
        $q->leftJoin('m.proprietario', 'p');    //utente
        
        $q->where($q->expr()->in('u.id', $contatti));
        $q->andWhere('p.id = :id_utente');        
        $q->andWhere('m.label LIKE :nome');
        $q->setParameter('id_utente', $utente->getId());
        $q->setParameter('nome', "{$lettera}%");
        
        $dql = $q->getQuery();
        //echo $dql->getSQL();
        $results = $dql->execute();
        
        return $results;
    }
    
    public function filtra_preferiti(\ES\UserBundle\Entity\User $utente) {
        $q = $this->createQueryBuilder('m');
        $q->leftJoin('m.contatto', 'u');    //utente
        $q->leftJoin('m.proprietario', 'p');    //utente
        
        $q->andWhere('p.id = :id_utente');        
        $q->andWhere('m.preferito LIKE :preferito');
        $q->setParameter('id_utente', $utente->getId());
        $q->setParameter('preferito', true);        
        
        $dql = $q->getQuery();
        //echo $dql->getSQL();
        $results = $dql->execute();
        
        return $results;
    }
    
    public function cercaContatto(\ES\UserBundle\Entity\User $utente, \ES\UserBundle\Entity\User $contatto) {
        $q = $this->createQueryBuilder('m');
        $q->leftJoin('m.contatto', 'u');    //utente
        $q->leftJoin('m.proprietario', 'p');    //utente
        
        $q->andWhere('p.id = :id_utente');        
        $q->andWhere('u.id LIKE :contatto');
        $q->setParameter('id_utente', $utente->getId());
        $q->setParameter('contatto', $contatto->getId());        
        
        $dql = $q->getQuery();
        //echo $dql->getSQL();
        $results = $dql->execute();
        return count($results) == 0 ? null : $results[0];
    }
    
}