<?php

namespace ES\CerMapBundle\Entity\Cer;

use Doctrine\ORM\EntityRepository;

/**
 * CERIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CerMotore extends EntityRepository {

    public function cerca($term) {
        $q = $this->createQueryBuilder('c');
        $sql_or = array();
        $sql_or[] = 'c.descrizione LIKE :titolo';
        $sql_or[] = 'c.codice LIKE :titolo';
        $q->where('c.categoria != :zero');
        $q->andWhere('(' . implode(') OR (', $sql_or) . ')');

        $dql = $this->getEntityManager()->createQuery($q->getDQL());
        $dql->setParameter('zero', "00");
        $dql->setParameter('titolo', "%{$term}%");

        $results = $dql->execute();

        $_out = $out = array();
        $i = 0;
        foreach ($results as $_result) {
            /* @var $_result \ES\CerMapBundle\Entity\Cer\Cer */
            $count = 0;
            preg_match_all("/{$term}/", $_result->getCodice(), $match);
            $count += count($match[0]) * 3;
            preg_match_all("/{$term}/", $_result->getDescrizione(), $match);
            $count += count($match[0]) * 1;
            $count = 100000 - $count * 1000 + $i++;
            $_out[$count] = array(
                'id' => $_result->getSlug(),
                'slug' => $_result->getSlug(),
                'pericoloso' => $_result->getPericoloso(),
                'classe' => $_result->getClasse(),
                'sottoclasse' => $_result->getSottoclasse(),
                'categoria' => $_result->getCategoria(),
                'descrizione' => $_result->getDescrizione(),
                'label' => "[{$_result->getCodice()}] {$_result->getDescrizione()}",
                'value' => "[{$_result->getCodice()}] {$_result->getDescrizione()}",
            );
            ksort($_out);
        }
        return $_out;
    }

    public function motore($term, $f_cer, $limit = 1000) {
        $pericoloso = null;
        if (!$f_cer['pericoloso'] && !$f_cer['non_pericoloso']) {
            return array(
                'totale' => 0,
                'results' => array(),
                'noresults' => true,
                'n' => array(
                    'pericolosi' => 0,
                    'non_pericolosi' => 0,
                ),
            );
        }
        if (!$f_cer['pericoloso'] && $f_cer['non_pericoloso']) {
            $pericoloso = false;
        }
        if ($f_cer['pericoloso'] && !$f_cer['non_pericoloso']) {
            $pericoloso = true;
        }
        $all = null;
        if (!$f_cer['complete'] && !$f_cer['alcune']) {
            return array(
                'totale' => 0,
                'results' => array(),
                'complete' => 0,
                'alcune' => 0,
                'noresults' => true,
                'n' => array(
                    'pericolosi' => 0,
                    'non_pericolosi' => 0,
                ),
            );
        }
        if (!$f_cer['complete'] && $f_cer['alcune']) {
            $all = false;
        }
        if ($f_cer['complete']) {
            $all = true;
            $f_cer['complete'] = false;
        }

        $results = array();
        $pericolosi = 0;
        $non_pericolosi = 0;
        $classi = 0;
        $sottoclassi = 0;
        $categorie = 0;

        if ($term && $term['find']) {
            $inner_join = array(
                'search_entities_words w' => 'w.entity_id = c.id',
            );

            $sql = "
SELECT c.id as cer, c.pericoloso, sum(w.recurrence) as punti, c.sottoclasse, c.categoria
  FROM cer_index c
            ";
            foreach ($inner_join as $tabella => $join) {
                $sql .= "
 INNER JOIN {$tabella} ON {$join}
            ";
            }
            $sql .= "
 WHERE w.word_id IN (" . implode(", ", $term['id']) . ")
            ";
            if (is_bool($pericoloso)) {
                $sql .= "
   AND c.pericoloso = " . ($pericoloso ? '1' : '0') . "             
            ";
            }
            if (!$f_cer['classi']) {
                $sql .= "
   AND c.sottoclasse != '00'             
            ";
            }
            if (!$f_cer['sottoclassi'] && $f_cer['classi']) {
                $sql .= "
   AND ((c.categoria = '00' AND c.sottoclasse = '00') OR c.categoria != '00')             
            ";
            }
            if (!$f_cer['sottoclassi'] && !$f_cer['classi']) {
                $sql .= "
   AND c.categoria != '00'             
            ";
            }
            if (!$f_cer['categorie']) {
                $sql .= "
   AND c.categoria = '00'             
            ";
            }
            $sql .= "
 GROUP BY c.id
HAVING count(*)" . ($all ? " = " : " < ") . count($term['id']) . " 
 ORDER BY punti DESC, codice ASC
 LIMIT 0, {$limit}
        ";

//            \EcoSeekr\Bundle\WebBundle\Functions\Funzioni::pr($sql, true);

            $connection = $this->getEntityManager()->getConnection();
            $stmt = $connection->executeQuery($sql);
            $results = $stmt->fetchAll();
            foreach ($results as $key => $rifiuto) {
                if ($rifiuto['pericoloso'] == 1) {
                    $pericolosi++;
                } else {
                    $non_pericolosi++;
                }
                if ($rifiuto['sottoclasse'] == '00') {
                    $classi++;
                } elseif ($rifiuto['categoria'] == '00') {
                    $sottoclassi++;
                } else {
                    $categorie++;
                }

                unset($results[$key][0], $results[$key][1], $results[$key][2]);
            }
        }
        $tot = count($results);
        $out = array(
            'totale' => $tot,
            'complete' => $all ? $tot : 0,
            'alcune' => $all ? 0 : $tot,
            'results' => $results,
            'noresults' => count($results) == 0,
            'n' => array(
                'pericolosi' => $pericolosi,
                'non_pericolosi' => $non_pericolosi,
                'classi' => $classi,
                'sottoclassi' => $sottoclassi,
                'categorie' => $categorie,
            ),
        );
        
        if($all && count($term['id']) > 1 && $out['totale'] < $limit) {
            $incompleti = $this->motore($term, $f_cer);
            $out['totale'] = $out['totale'] + $incompleti['totale'];
            $out['complete'] = $out['complete'] + $incompleti['complete'];
            $out['alcune'] = $out['alcune'] + $incompleti['alcune'];
            $out['results'] = array_merge($out['results'], $incompleti['results']);
            $out['noresults'] = $out['noresults'] && $incompleti['noresults'];
            $out['n']['pericolosi'] = $out['n']['pericolosi'] + $incompleti['n']['pericolosi'];
            $out['n']['non_pericolosi'] = $out['n']['non_pericolosi'] + $incompleti['n']['non_pericolosi'];
            $out['n']['classi'] = $out['n']['classi'] + $incompleti['n']['classi'];
            $out['n']['sottoclassi'] = $out['n']['sottoclassi'] + $incompleti['n']['sottoclassi'];
            $out['n']['categorie'] = $out['n']['categorie'] + $incompleti['n']['categorie'];
        }

        return $out;
    }

    function getResults($results) {
        $ids = array();
        $out = array();
        $pericolosi = 0;
        $non_pericolosi = 0;
        foreach ($results as $_key => $_result) {
            if (!in_array($_result['cer'], $ids)) {
                $ids[] = $_result['cer'];
                $found = array('word');
                $punti = $_result['punti'];
                $pericoloso = $_result['pericoloso'];
                if ($pericoloso == 1) {
                    $pericolosi++;
                } else {
                    $non_pericolosi++;
                }
                $result = $this->find($_result['cer']);

                $out[$result->getId()] = array(
                    'show' => true,
                    'punti' => $punti,
                    'found' => $found,
                    'result' => array(
                        'id' => $result->getId(),
                        'result' => 'rifiuto',
                        'route' => $result->getExtraField(),
                        'slug' => $result->getSlug(),
                        'titolo' => $result->getTitolo(),
                        'data' => array(
                            'codice' => $result->getCodice(),
                            'classe' => $result->getClasse(),
                            'sottoclasse' => $result->getSottoclasse(),
                            'categoria' => $result->getCategoria(),
                            'descrizione' => $result->getDescrizione(),
                            'pericoloso' => $result->getPericoloso(),
                        ),
                    )
                );
            }
        }

//        Funzioni::vd($out);

        return $out;
    }

}