<?php

namespace ES\CerMapBundle\Entity\Cer;

/**
 * CERIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CerRepository extends CerMotore {

    public function getArray() {
        $out = array();
        foreach($this->findAll() as $cer) {
            $out[$cer->getCodice()] = $cer->getId();
        }
        return $out;
    }
    
}