<?php

namespace ES\MessengerBundle\Entity\RDO;

use Doctrine\ORM\EntityRepository;

/**
 * CerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CerRepository extends EntityRepository
{
    /*
     * Select * FROM `msg_rdo_cer` c LEFT JOIN `op_showroom` s ON c.from_showroom_id = s.id WHERE c.from_showroom_id IS NOT NULL AND  s.user_id IS NULL GROUP BY c.id 
     * Ritorna la lista di cer con showroom non attivati, da chiamare noi
     */
    public function getGestioneRdoCer() {
        $q = $this->createQueryBuilder('c');
        $q->leftJoin('c.from_showroom', 's'); //è il nome della variabile che impersonifica la tabella (la chiave esternba)
        
        $q->where('s.user IS NULL');
        $q->groupBy('c.id');

        $dql = $q->getQuery();
        $results = $dql->execute();

        return $results;
    }
    
    public function getGestioneRdoCerCentroSmaltimento() {
        $q = $this->createQueryBuilder('c');
        
        $q->where('c.from_showroom IS NULL');

        $dql = $q->getQuery();
        $results = $dql->execute();

        return $results;
    }
    
}