<?php

namespace ES\MessengerBundle\Entity\RDO;

use Doctrine\ORM\EntityRepository;

/**
 * CerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MpsRepository extends EntityRepository
{
    /*
     * Ritorna la lista di mps con showroom non attivati, da chiamare noi
     */
    public function getGestioneRdoMps() {
        $q = $this->createQueryBuilder('m');
        $q->leftJoin('m.from_showroom', 's'); //è il nome della variabile che impersonifica la tabella (la chiave esternba)
        
        $q->where('s.user IS NULL');
        $q->andWhere('m.from_showroom IS NOT NULL');

        $dql = $q->getQuery();
        $results = $dql->execute();

        return $results;
    }
    
    
}