<?php

namespace ES\MessengerBundle\Entity\RDO;

use Doctrine\ORM\EntityRepository;

/**
 * CerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiziRepository extends EntityRepository
{
}