framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~
    
# Parameters Configuration
parameters:
    running_mode: %environment%
    proxy.ip: false    
    email_messenger: %mail_messenger%
    
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_stats: ~
        app_name: %app_name%
        app_email: %app_email%
        dimensione_massima_immagine: %dimensione_massima_immagine%
        larghezza_minima_immagine: %larghezza_minima_immagine%
        altezza_minima_immagine: %altezza_minima_immagine%
        pagina_principale: %pagina_principale%
        node_server:    %node.server%
        node_cermap_port: %node.cermap.port%
        analytics_id: %analytics.id%
        analytics_site: %analytics.site%
        analytics_ids: %analytics.ids%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    # bundles:        [ ]
    #java: /usr/bin/java
    ruby: %ruby%
    filters:
        cssrewrite: ~
        scss:       
          bin: %scss%
        compass:   
          bin: %compass%
          load_paths: [%compass_load_path%/compass-normalize-1.4.2/stylesheets, %compass_load_path%/breakpoint-1.3/stylesheets, %compass_load_path%/compass-recipes-0.3.0/stylesheets, %compass_load_path%/sassy-buttons-0.1.4/stylesheets, %compass_load_path%/animate-sass-0.1.1/stylesheets]
          apply_to: "\.scss$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
#GEDMO SLUG
#https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst
stof_doctrine_extensions:
    default_locale: en_US

    orm:
        default: 
            timestampable:  true
            sluggable:      true
            translatable:   true    
            
fos_facebook:
    alias:  facebook
    app_id: %facebook.app_id%
    secret: %facebook.app_secret%
    cookie: true
    permissions: [email, read_friendlists, user_birthday, user_photos, user_about_me, user_activities, user_location, publish_stream]

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ES\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        #form type serve a sovrascrivere il form di registrazione di FOS, love_user_registration è ul nome del form
        form:
            type: es_user_registration #form personale
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Email:registrazioneAccount.txt.twig
            
            from_email:
                address:        ecoseekr.italia@gmail.com
                sender_name:    Attivazione Ecoseekr
    resetting:
        email:
            from_email:
                address:        ecoseekr.italia@gmail.com
                sender_name:    Recupero Password Ecoseekr
                
ephp_acl:
    user_class: ES\UserBundle\Entity\User
    facebook:
        app_id: %facebook.app_id%
        app_secret: %facebook.app_secret%
        app_name: %app_name%
        app_url: %app_url%
        app_description: %app_description%     
        
services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }
         
    
    
presta_sitemap:
    timetolive:           3600
    dumper_base_url:      http://www.ecoseekr.it/
    route_annotation_listener:  true

ivory_google_map:
    marker:
        # Your own marker image class
        #class: "My\Fucking\MarkerImage"

        # Your own marker image helper class
        #helper_class: "My\Fucking\MarkerImageHelper"

        # Prefix used for the generation of the marker image javascript variable
        #prefix_javascript_variable: "marker_image_"

        # Url of the marker image
        #url: "/bundles/esweb/images/form/check_big.png"

        # Anchor of the marker image
        # By default, there is no anchor
        #anchor:
        #    x: 20
        #    y: 34

        # Origin of the marker image
        # By default, there is no origin
        #origin:
        #    x: 0
        #    y: 0

        # Size of the marker
        # By default, there is no size
        #size:
        #    width: 10
        #    height: 34
        #    width_unit: "px"
        #    height_unit: "px"

        # Scaled size of the marker image
        # By default there is not scaled size
        #scaled_size:
        #    width: 10
        #    height: 34
        #    width_unit: "px"
        #    height_unit: "px"
