imports:
    - { resource: config.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
   
framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false
    
twig:
    globals:
        analytics_id: false
        analytics_name: false
        analytics_ids: false
        
monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: false

swiftmailer:
    transport: gmail
    username:  %username_gmail%
    password:  %password_gmail%    
    delivery_address: ecoseekr.italia+dev@gmail.com
