jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_COMM:        ROLE_USER
        ROLE_ADMIN:       ROLE_COMM
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    cermaps: { password: develop, roles: [ 'ROLE_SUPER_ADMIN' ] } 
                    dodo:  { password: pci, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    barno: { password: hellokitty, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    gabriele: { password: sonogay, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    gimoz71: { password: lovecraft, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    federica.terreni: { password: ecoseekr, roles: [ 'ROLE_ADMIN' ] }
                    andrea.lanzetta: { password: toscana, roles: [ 'ROLE_COMM' ] }
                    stefano.federigi: { password: ecoseekr, roles: [ 'ROLE_COMM' ] }
# Tolte il 25/07/2013 per inandempienza                    
#                    massimiliano.radaelli: { password: ecoseekr, roles: [ 'ROLE_COMM' ] }
#                    simone.bellutti: { password: ecoseekr, roles: [ 'ROLE_COMM' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        admin:
            pattern: ^/
            provider: in_memory
            stateless: true
            http_basic:
                realm: "Admin Area"
        login:
            pattern:  ^/login$
            security: false

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
