<?php

namespace ES\OperatoriBundle\Entity\Servizi;

use Doctrine\ORM\EntityRepository;

/**
 * ServizioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServizioRepository extends EntityRepository
{
}
