<?php

namespace ES\CerMapBundle\Entity\Recuperabili;

use Doctrine\ORM\EntityRepository;

/**
 * CategoriaRifiutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository {

    function findPrevNext($id, $pericoloso) {
        $q_prev = $this->createQueryBuilder('r')
                ->where('r.id < :id')
                ->andWhere('r.pericoloso = :pericoloso')
                ->orderBy('r.id', 'DESC')
        ;
        $dql_prev = $this->getEntityManager()->createQuery($q_prev->getDQL());
        $dql_prev->setParameter('id', $id);
        $dql_prev->setParameter('pericoloso', $pericoloso);
        $prev = $this->getFirstOrNull($dql_prev);
        if (!$prev) {
            $q_prev = $this->createQueryBuilder('r')
                    ->where('r.id > :id')
                    ->andWhere('r.pericoloso = :pericoloso')
                    ->orderBy('r.id', 'DESC')
            ;
            $dql_prev = $this->getEntityManager()->createQuery($q_prev->getDQL());
            $dql_prev->setParameter('id', $id);
            $dql_prev->setParameter('pericoloso', $pericoloso);
            $prev = $this->getFirstOrNull($dql_prev);
            ;
        }

        $q_next = $this->createQueryBuilder('r')
                ->where('r.id > :id')
                ->andWhere('r.pericoloso = :pericoloso')
                ->orderBy('r.id', 'ASC')
        ;
        $dql_next = $this->getEntityManager()->createQuery($q_next->getDQL());
        $dql_next->setParameter('id', $id);
        $dql_next->setParameter('pericoloso', $pericoloso);
        $next = $this->getFirstOrNull($dql_next);
        if (!$next) {
            $q_next = $this->createQueryBuilder('r')
                    ->where('r.id < :id')
                    ->andWhere('r.pericoloso = :pericoloso')
                    ->orderBy('r.id', 'ASC')
            ;
            $dql_next = $this->getEntityManager()->createQuery($q_next->getDQL());
            $dql_next->setParameter('id', $id);
            $dql_next->setParameter('pericoloso', $pericoloso);
            $next = $this->getFirstOrNull($dql_next);
        }
        return array('prev' => $prev ? array('slug' => $prev->getSlug(), 'titolo' => $prev->getNome()) : null, 'next' => $next ? array('slug' => $next->getSlug(), 'titolo' => $next->getNome()) : null);
    }
    
    private function getFirstOrNull(\Doctrine\ORM\Query $dql) {
        $result = $dql->execute();
        if (is_array($result)) {
            return array_shift($result);
        }
        return $result;
    }
}