<?php

namespace ES\CerMapBundle\Entity\Recuperabili;

use Doctrine\ORM\EntityRepository;

/**
 * RifiutiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RifiutoMotore extends EntityRepository {

    public function cerca($term, $pericoloso = null) {
        $q = $this->createQueryBuilder('r');
        $q->leftJoin('r.attivita_recupero', 'a');
        $q->leftJoin('r.cer', 'c');

        $sql_or = array();
        $sql_or[] = 'r.rifiuto LIKE :titolo';
        $sql_or[] = 'r.sottotitolo LIKE :titolo';
        $sql_or[] = 'r.tipologia LIKE :titolo';
        $sql_or[] = 'r.provenienza LIKE :titolo';
        $sql_or[] = 'r.caratteristiche LIKE :titolo';
        $sql_or[] = 'a.attivita LIKE :titolo';
        $sql_or[] = 'a.caratteristiche_mps LIKE :titolo';
        $sql_or[] = 'c.descrizione LIKE :titolo';
        $sql_or[] = 'c.codice LIKE :titolo';

        $q->andWhere('(' . implode(') OR (', $sql_or) . ')');

        if ($pericoloso !== null) {
            $q->leftJoin('r.categoria', 'cat');
            $q->andWhere('cat.pericoloso = :pericoloso');
            $q->setParameter('pericoloso', $pericoloso);
        }

        $dql = $q->getQuery();
        $dql->setParameter('titolo', "%{$term}%");

        $results = $dql->execute();

        $_out = $out = array();
        $i = 0;
        foreach ($results as $_result) {
            /* @var $_result \ES\CerMapBundle\Entity\Recuperabili\Rifiuto */
            $count = 0;
            preg_match_all("/{$term}/", $_result->getRifiuto(), $match);
            $count += count($match[0]) * 5;
            preg_match_all("/{$term}/", $_result->getSottotitolo(), $match);
            $count += count($match[0]) * 4;
            preg_match_all("/{$term}/", $_result->getTipologia(), $match);
            $count += count($match[0]) * 3;
            preg_match_all("/{$term}/", $_result->getProvenienza(), $match);
            $count += count($match[0]) * 2;
            preg_match_all("/{$term}/", $_result->getCaratteristiche(), $match);
            $count += count($match[0]) * 2;
            foreach ($_result->getAttivitaRecupero() as $attivita) {
                preg_match_all("/{$term}/", $attivita->getAttivita(), $match);
                $count += count($match[0]) * 1;
                preg_match_all("/{$term}/", $attivita->getCaratteristicheMps(), $match);
                $count += count($match[0]) * 1;
            }
            foreach ($_result->getCer() as $cer) {
                preg_match_all("/{$term}/", $cer->getCodice(), $match);
                $count += count($match[0]) * 1;
                preg_match_all("/{$term}/", $cer->getDescrizione(), $match);
                $count += count($match[0]) * 1;
            }
            $count = 100000 - $count * 1000 + $i++;
            $_out[$count] = array(
                'id' => $_result->getSlug(),
                'slug' => $_result->getSlug(),
                'label' => $_result->getRifiuto(),
                'value' => $_result->getRifiuto(),
                'rifiuto' => $_result->getRifiuto(),
                'tipologia' => $_result->getTipologia(),
                'categoria' => $_result->getCategoria()->getNome(),
            );
            ksort($_out);
        }
        return $_out;
    }

    public function motore($term, $f_rifiuti, $limit = 1000) {
        $pericoloso = null;
        if (!$f_rifiuti['pericoloso'] && !$f_rifiuti['non_pericoloso']) {
            return array(
                'totale' => 0,
                'results' => array(),
                'complete' => 0,
                'alcune' => 0,
                'noresults' => true,
                'n' => array(
                    'pericolosi' => 0,
                    'non_pericolosi' => 0,
                ),
            );
        }
        if (!$f_rifiuti['pericoloso'] && $f_rifiuti['non_pericoloso']) {
            $pericoloso = false;
        }
        if ($f_rifiuti['pericoloso'] && !$f_rifiuti['non_pericoloso']) {
            $pericoloso = true;
        }
        $all = null;
        if (!$f_rifiuti['complete'] && !$f_rifiuti['alcune']) {
            return array(
                'totale' => 0,
                'results' => array(),
                'complete' => 0,
                'alcune' => 0,
                'noresults' => true,
                'n' => array(
                    'pericolosi' => 0,
                    'non_pericolosi' => 0,
                ),
            );
        }
        if (!$f_rifiuti['complete'] && $f_rifiuti['alcune']) {
            $all = false;
        }
        if ($f_rifiuti['complete']) {
            $all = true;
            $f_rifiuti['complete'] = false;
        }

        $results = array();
        $pericolosi = 0;
        $non_pericolosi = 0;

        if ($term && $term['find']) {
            $inner_join = array(
                'cer_categorie_rifiuti c' => 'r.categoria_id = c.id',
                'search_entities_words w' => 'w.entity_id = r.id',
            );

            $sql = "
SELECT r.id as recuperabile, c.pericoloso, sum(w.recurrence) as punti
  FROM cer_rifiuti r
            ";
            foreach ($inner_join as $tabella => $join) {
                $sql .= "
 INNER JOIN {$tabella} ON {$join}
            ";
            }
            $sql .= "
 WHERE w.word_id IN (" . implode(", ", $term['id']) . ")
            ";
            if (is_bool($pericoloso)) {
                $sql .= "
   AND c.pericoloso = " . ($pericoloso ? '1' : '0') . "             
            ";
            }
            $sql .= "
 GROUP BY r.id
HAVING count(*)" . ($all ? " = " : " < ") . count($term['id']) . " 
 ORDER BY punti DESC
 LIMIT 0, {$limit}
        ";

//            \EcoSeekr\Bundle\WebBundle\Functions\Funzioni::pr($sql, true);

            $connection = $this->getEntityManager()->getConnection();
            $stmt = $connection->executeQuery($sql);
            $results = $stmt->fetchAll();
            foreach ($results as $key => $rifiuto) {
                if ($rifiuto['pericoloso'] == 1) {
                    $pericolosi++;
                } else {
                    $non_pericolosi++;
                }
                unset($results[$key][0], $results[$key][1], $results[$key][2]);
            }
        }
        $tot = count($results);
        $out = array(
            'totale' => $tot,
            'complete' => $all ? $tot : 0,
            'alcune' => $all ? 0 : $tot,
            'results' => $results,
            'noresults' => count($results) == 0,
            'n' => array(
                'pericolosi' => $pericolosi,
                'non_pericolosi' => $non_pericolosi,
            ),
        );
        
        if($all && count($term['id']) > 1 && $out['totale'] < $limit) {
            $incompleti = $this->motore($term, $f_rifiuti);
            $out['totale'] = $out['totale'] + $incompleti['totale'];
            $out['complete'] = $out['complete'] + $incompleti['complete'];
            $out['alcune'] = $out['alcune'] + $incompleti['alcune'];
            $out['results'] = array_merge($out['results'], $incompleti['results']);
            $out['noresults'] = $out['noresults'] && $incompleti['noresults'];
            $out['n']['pericolosi'] = $out['n']['pericolosi'] + $incompleti['n']['pericolosi'];
            $out['n']['non_pericolosi'] = $out['n']['non_pericolosi'] + $incompleti['n']['non_pericolosi'];
        }

        return $out;
    }

    function getResults($results) {
        $ids = array();
        $out = array();
        $pericolosi = 0;
        $non_pericolosi = 0;
        foreach ($results as $_key => $_result) {
            if (!in_array($_result['recuperabile'], $ids)) {
                $ids[] = $_result['recuperabile'];
                $_s = microtime(true);
                $found = array('word');
                $punti = $_result['punti'];
                $pericoloso = $_result['pericoloso'];
                if ($pericoloso == 1) {
                    $pericolosi++;
                } else {
                    $non_pericolosi++;
                }
                $result = $this->find($_result['recuperabile']);

                $out[$result->getId()] = array(
                    'show' => true,
                    'punti' => $punti,
                    'found' => $found,
                    'result' => array(
                        'id' => $result->getId(),
                        'result' => 'rifiuto',
                        'route' => $result->getExtraField(),
                        'slug' => $result->getSlug(),
                        'titolo' => $result->getTitolo(),
                        'data' => array(
                            'tipologia' => $result->getTipologia(),
                            'categoria' => array(
                                'nome' => $result->getCategoria()->getNome(),
                                'categoria' => $result->getCategoria()->getCategoria(),
                                'pericoloso' => $pericoloso,
                            ),
                        ),
                    )
                );
            }
        }

//        Funzioni::vd($out);

        return $out;
    }

}