<?php

namespace ES\CerMapBundle\Entity\Recuperabili;

use Doctrine\ORM\EntityRepository;

/**
 * SmaltimentoRecuperoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmaltimentoRecuperoRepository extends EntityRepository
{
}